worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: debug

is-testing: true

secret-key: 'YI>(b-]gk9t{0Oa0iYe:s8~[(l?e_^7i'

# pg_grpc_service_template_db-1 is the service name + _ + filename of the db_1.sql
dbconnection: 'postgresql://testsuite@localhost:15433/auth_service_db_1'
